# Generated by Django 5.2.4 on 2025-07-15 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='基金名称')),
                ('description', models.TextField(verbose_name='基金用途描述')),
                ('wallet_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='关联钱包地址')),
                ('fund_type', models.CharField(choices=[('REWARD', '奖励基金'), ('STABILITY', '稳定基金'), ('GRANT', '激励基金'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='基金类型')),
            ],
            options={
                'verbose_name': '公共基金池',
                'verbose_name_plural': '公共基金池',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('NEWS', '新闻动态'), ('ANNOUNCEMENT', '官方公告'), ('REPORT', '透明度报告')], default='NEWS', max_length=20, verbose_name='分类')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('author', models.CharField(default='ACC Foundation', max_length=100, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章与公告',
                'verbose_name_plural': '文章与公告',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('developer_info', models.CharField(max_length=200, verbose_name='开发者/团队信息')),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='资助金额 (USD)')),
                ('status', models.CharField(choices=[('APPLIED', '申请中'), ('REVIEWING', '审核中'), ('FUNDED', '已资助'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成')], default='APPLIED', max_length=20, verbose_name='项目状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='项目开始日期')),
            ],
            options={
                'verbose_name': '生态激励项目',
                'verbose_name_plural': '生态激励项目',
                'ordering': ['-start_date'],
            },
        ),
    ]
