# Generated by Django 5.2.4 on 2025-07-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/', verbose_name='封面图片'),
        ),
    ]
