# Generated by Django 5.2.4 on 2025-07-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_cover_image_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='设为精选项目'),
        ),
    ]
