# Generated by Django 5.2.4 on 2025-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attachment',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/', verbose_name='附件下载'),
        ),
    ]
